version: '3.8'

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
    networks:
      - network_default

  mongo:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - network_default
    healthcheck:
      test: "mongosh --eval 'print(\"waited for connection\")'"
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 15s

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: guest
      ME_CONFIG_BASICAUTH_PASSWORD: guest
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
    links:
      - mongo
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - network_default

  consumer-users:
    container_name: consumer-users
    build:
      context: .
      dockerfile: consumer-amqp.Dockerfile
    image: consumer-rabbitmq:v2
    environment:
      RESOURCE_TYPE: users
    env_file:
      - .env_consumer
    networks:
      - network_default

  consumer-albums:
    container_name: consumer-albums
    image: consumer-rabbitmq:v2
    environment:
      RESOURCE_TYPE: albums
    env_file:
      - .env_consumer
    networks:
      - network_default

  consumer-posts:
    container_name: consumer-posts
    image: consumer-rabbitmq:v2
    environment:
      RESOURCE_TYPE: posts
    env_file:
      - .env_consumer
    networks:
      - network_default

  consumer-photos:
    container_name: consumer-photos
    image: consumer-rabbitmq:v2
    environment:
      RESOURCE_TYPE: photos
    env_file:
      - .env_consumer
    networks:
      - network_default

  consumer-comments:
    container_name: consumer-comments
    image: consumer-rabbitmq:v2
    environment:
      RESOURCE_TYPE: comments
    env_file:
      - .env_consumer
    networks:
      - network_default

  consumer-todos:
    container_name: consumer-todos
    image: consumer-rabbitmq:v2
    environment:
      RESOURCE_TYPE: todos
    env_file:
      - .env_consumer
    networks:
      - network_default

networks:
  network_default:
    name: network_default
    driver: bridge
