version: '3.8'

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
    networks:
      - rabbitmq_network

  mongo:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - mongodb_network

networks:
  rabbitmq_network:
    name: network_default
    driver: bridge
  mongodb_network:
    name: network_default
    driver: bridge